apiVersion: v1
kind: Pod
metadata:
  name: locust-user
spec:
  restartPolicy: Never
  containers:
    - name: locust
      image: locust-custom:latest
      imagePullPolicy: Never
      command: ["locust"]
      args:
        ["-f", "/mnt/user_service.py",
         "--host=http://user-service:8700",
         "--users=10",
         "--spawn-rate=2",
         "--run-time=1m",
         "--headless"]