apiVersion: v1
kind: Pod
metadata:
  name: locust-shipping
spec:
  restartPolicy: Never
  containers:
    - name: locust
      image: locust-custom:latest
      command: ["locust"]
      args:
        ["-f", "/mnt/shipping_service.py",
         "--host=http://shipping-service:8600",
         "--users=10",
         "--spawn-rate=2",
         "--run-time=1m",
         "--headless"]
      imagePullPolicy: Never