apiVersion: v1
kind: Pod
metadata:
  name: locust-product
spec:
  restartPolicy: Never
  containers:
    - name: locust
      image: locust-custom:latest
      command: ["locust"]
      args:
        ["-f", "/mnt/product_service.py",
         "--host=http://product-service:8500",
         "--users=10",
         "--spawn-rate=2",
         "--run-time=1m",
         "--headless"]
      imagePullPolicy: Never