name: CD - Stage Deployment

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]
  workflow_dispatch:

concurrency:
  group: cd-stage
  cancel-in-progress: true

jobs:
  terraform_deploy:
    name: Terraform Apply (Stage)
    runs-on: [self-hosted, Windows]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Minikube is Running
        shell: pwsh
        run: |
          Write-Host "Checking Minikube status..."

          $status = minikube status --format "{{.Host}}" 2>$null

          if ($status -eq "Running") {
            Write-Host "Minikube is already running."
          }
          else {
            Write-Host "Minikube is NOT running. Attempting to start it..."
            try {
              minikube start --driver=docker
            }
            catch {
              Write-Host "Minikube failed to start, attempting full reset..."
              minikube delete
              minikube start --driver=docker
            }
          }

          Write-Host "Setting Minikube as active Kubernetes context..."
          kubectl config use-context minikube

      - name: Configure Terraform
        run: terraform -version

      - name: Terraform Init (Stage)
        working-directory: terraform/environments/stage
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: terraform init

      - name: Select Workspace
        working-directory: terraform/environments/stage
        run: |
          terraform workspace select ecommerce-stage || terraform workspace new ecommerce-stage

      - name: Terraform Plan
        working-directory: terraform/environments/stage
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/environments/stage
        run: terraform apply -auto-approve


      - name: Configure Terraform
        run: |
          terraform -version

      - name: Terraform Init (Stage)
        working-directory: terraform/environments/stage
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          terraform init

      - name: Select Workspace
        working-directory: terraform/environments/stage
        run: |
          terraform workspace select ecommerce-stage || terraform workspace new ecommerce-stage

      - name: Terraform Plan
        working-directory: terraform/environments/stage
        run: |
          terraform plan

      - name: Terraform Apply
        working-directory: terraform/environments/stage
        run: |
          terraform apply -auto-approve

  wait_for_services:
    name: Wait for Stage Services
    runs-on: [self-hosted, Windows]
    needs: terraform_deploy

    steps:
      - name: Wait for all pods in stage namespace
        run: |
          kubectl wait --namespace stage --for=condition=ready pod --all --timeout=600s

      - name: List deployments, pods, services
        run: |
          kubectl get deployments -n stage
          kubectl get pods -n stage
          kubectl get svc -n stage

  performance_tests:
    name: Performance Test â€¢ ${{ matrix.service }}
    runs-on: [self-hosted, Windows]
    needs: wait_for_services

    strategy:
      fail-fast: false
      matrix:
        service:
          - user
          - product
          - shipping

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load Locust Image
        run: |
          docker build -t locust-custom:latest -f Dockerfile.locust .
          minikube image load locust-custom:latest

      - name: Run Locust Scenario
        run: |
          echo "Running Locust tests for ${{ matrix.service }}..."
          kubectl apply -n stage -f k8s/performance/locust-${{ matrix.service }}.yml

          kubectl wait -n stage \
            --for=condition=Ready pod/locust-${{ matrix.service }} \
            --timeout=600s

          kubectl logs -n stage pod/locust-${{ matrix.service }}

          kubectl delete

      - name: Save Logs
        run: |
          kubectl logs -n stage pod/locust-${{ matrix.service }} > locust-${{ matrix.service }}.log

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: locust-${{ matrix.service }}-logs
          path: locust-${{ matrix.service }}.log

  notify:
      name: Notify on Failure
      runs-on: ubuntu-latest
      needs: [terraform_deploy, wait_for_services, performance_tests]
      
      steps:
        - name: Notify by Email on Failure
          if: failure()
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USER }}
            password: ${{ secrets.EMAIL_PASS }}
            subject: "Pipeline FAILED - ${{ github.workflow }} / Job: ${{ github.job }}"
            to: ${{ secrets.EMAIL_TO }}
            from: "GitHub CI/CD Bot <${{ secrets.EMAIL_USER }}>"
            body: |
              Pipeline failure detected

              Repository:  ${{ github.repository }}
              Branch:      ${{ github.ref_name }}
              Workflow:    ${{ github.workflow }}
              Job:         ${{ github.job }}
              Commit:      ${{ github.sha }}
              Autor:       ${{ github.actor }}
              URL:         https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

              Revisa los logs inmediatamente.