name: CD - Stage Deployment

on:
  push:
    branches: [ stage, featue/cd ]
  pull_request:
    branches: [ stage ]
  workflow_dispatch:

concurrency:
  group: cd-stage
  cancel-in-progress: true

jobs:
  security_scan:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner (Repo)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-repo-results.txt'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Print Trivy results
        if: always()
        run: cat trivy-repo-results.txt

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-repo-results-ci-stage
          path: trivy-repo-results.txt

  deploy:
    name: Deploy
    runs-on: [self-hosted, Windows]
    needs: security_scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Minikube Status
        id: minikube_check
        shell: pwsh
        run: |
          Write-Host "Checking Minikube status..."
          $status = minikube status --format "{{.Host}}" 2>$null
          
          if ($status -eq "Running") {
            Write-Host "Minikube is running."
            echo "minikube_running=true" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "Minikube is NOT running."
            echo "minikube_running=false" >> $env:GITHUB_OUTPUT
          }

      - name: Start Minikube if Stopped
        if: steps.minikube_check.outputs.minikube_running == 'false'
        shell: pwsh
        run: |
          Write-Host "Starting Minikube..."
          try {
            minikube start --driver=docker
          } catch {
            Write-Host "Failed to start, deleting and recreating..."
            minikube delete
            minikube start --driver=docker
          }

      - name: Create Stage Namespace
        shell: pwsh
        run: |
          kubectl create namespace stage --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Kubernetes Resources
        shell: pwsh
        run: |
          Write-Host "Applying Kubernetes manifests for stage environment..."
          kubectl apply -f k8s/ -n stage
          
      - name: Restart deployments if already running
        shell: pwsh
        run: |
          Write-Host "Restarting all deployments in stage namespace..."
          kubectl rollout restart deployment -n stage

  wait_for_services:
    name: Wait for Stage Services
    runs-on: [self-hosted, Windows]
    needs: deploy

    steps:
      - name: Wait for all pods in stage namespace
        run: |
          kubectl wait --namespace stage --for=condition=ready pod --all --timeout=600s

      - name: List deployments, pods, services
        run: |
          kubectl get deployments -n stage
          kubectl get pods -n stage
          kubectl get svc -n stage

  performance_tests:
    name: Performance Test â€¢ ${{ matrix.service }}
    runs-on: [self-hosted, Windows]
    needs: wait_for_services

    strategy:
      fail-fast: false
      matrix:
        service:
          - user
          - product
          - shipping

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load Locust Image
        run: |
          docker build -t locust-custom:latest -f Dockerfile.locust .
          minikube image load locust-custom:latest

      - name: Run Locust Scenario
        run: |
          echo "Running Locust tests for ${{ matrix.service }}..."
          kubectl apply -n stage -f k8s/performance/locust-${{ matrix.service }}.yml

          # Wait for the pod to be ready (running)
          kubectl wait -n stage \
            --for=condition=Ready pod/locust-${{ matrix.service }} \
            --timeout=600s

          # Wait for the test to complete (approx 1m run time)
          Start-Sleep -Seconds 70

      - name: Save Logs
        run: |
          kubectl logs -n stage pod/locust-${{ matrix.service }} > locust-${{ matrix.service }}.log

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: locust-${{ matrix.service }}-logs
          path: locust-${{ matrix.service }}.log

      - name: Cleanup Locust Pod
        if: always()
        run: |
          kubectl delete -n stage -f k8s/performance/locust-${{ matrix.service }}.yml --ignore-not-found=true

  notify:
      name: Notify on Failure
      runs-on: ubuntu-latest
      needs: [deploy, wait_for_services, performance_tests]
      if: failure()
      
      steps:
        - name: Notify by Email on Failure
          if: failure()
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USER }}
            password: ${{ secrets.EMAIL_PASS }}
            subject: "Pipeline FAILED - ${{ github.workflow }} / Job: ${{ github.job }}"
            to: ${{ secrets.EMAIL_TO }}
            from: "GitHub CI/CD Bot <${{ secrets.EMAIL_USER }}>"
            body: |
              Pipeline failure detected

              Repository:  ${{ github.repository }}
              Branch:      ${{ github.ref_name }}
              Workflow:    ${{ github.workflow }}
              Job:         ${{ github.job }}
              Commit:      ${{ github.sha }}
              Autor:       ${{ github.actor }}
              URL:         https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

              Revisa los logs inmediatamente.